import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';
import type { Command } from 'commander';
import { loadConfig } from '../core/config.js';
import { walkHierarchy } from '../core/fs-walker.js';
import { parseMarkdown } from '../core/markdown-parser.js';
import { parseImplData } from '../core/impl-reader.js';
import type { FolderNode } from '../validators/types.js';

// ─── Data model ───────────────────────────────────────────────────────────────

interface OverviewIntent {
  name: string;
  path: string;
  goal: string;
  state: string;
  behaviours: OverviewBehaviour[];
}

interface OverviewBehaviour {
  name: string;
  path: string;
  actor: string;
  state: string;
  implementations: OverviewImpl[];
  subBehaviours: OverviewBehaviour[];
}

interface OverviewImpl {
  name: string;
  path: string;
  state: string;
  commitCount: number;
  testCount: number;
}

// ─── Extraction helpers ───────────────────────────────────────────────────────

function readSection(filePath: string, section: string): string {
  try {
    const content = readFileSync(filePath, 'utf-8');
    const doc = parseMarkdown(filePath, content);
    return doc.sections.get(section)?.rawBody.trim() ?? '';
  } catch { return ''; }
}

function readState(filePath: string): string {
  try {
    const content = readFileSync(filePath, 'utf-8');
    const doc = parseMarkdown(filePath, content);
    const status = doc.sections.get('status');
    const match = /\*\*State:\*\*\s*(\S+)/.exec(status?.rawBody ?? '');
    return match?.[1]?.trim() ?? 'unknown';
  } catch { return 'unknown'; }
}

function buildImpl(node: FolderNode): OverviewImpl {
  const filePath = join(node.absolutePath, 'impl.md');
  const state = readState(filePath);
  let commitCount = 0;
  let testCount = 0;
  try {
    const content = readFileSync(filePath, 'utf-8');
    const doc = parseMarkdown(filePath, content);
    const data = parseImplData(doc);
    commitCount = data.commits.length;
    testCount = data.testFiles.length;
  } catch { /* use defaults */ }
  return { name: node.name, path: `./${node.relativePath}/impl.md`, state, commitCount, testCount };
}

function buildBehaviour(node: FolderNode): OverviewBehaviour {
  const filePath = join(node.absolutePath, 'usecase.md');
  const state = readState(filePath);
  const actorRaw = readSection(filePath, 'actor');
  const actor = actorRaw.replace(/<[^>]+>/g, '').split('\n')[0]?.trim() ?? '';
  const implementations: OverviewImpl[] = [];
  const subBehaviours: OverviewBehaviour[] = [];
  for (const child of node.children) {
    if (child.marker === 'impl') implementations.push(buildImpl(child));
    else if (child.marker === 'behaviour') subBehaviours.push(buildBehaviour(child));
  }
  return { name: node.name, path: `./${node.relativePath}/usecase.md`, actor, state, implementations, subBehaviours };
}

function buildIntent(node: FolderNode): OverviewIntent {
  const filePath = join(node.absolutePath, 'intent.md');
  const state = readState(filePath);
  const goalRaw = readSection(filePath, 'goal');
  // Strip template placeholders, take first sentence
  const goal = goalRaw.replace(/<[^>]+>/g, '').split(/\.\s+/)[0]?.trim() ?? '';
  const behaviours: OverviewBehaviour[] = [];
  for (const child of node.children) {
    if (child.marker === 'behaviour') behaviours.push(buildBehaviour(child));
  }
  return { name: node.name, path: `./${node.relativePath}/intent.md`, goal, state, behaviours };
}

// ─── Formatters ───────────────────────────────────────────────────────────────

function implCounts(b: OverviewBehaviour): { total: number; complete: number } {
  let total = b.implementations.length;
  let complete = b.implementations.filter(i => i.state === 'complete').length;
  for (const sub of b.subBehaviours) {
    const c = implCounts(sub);
    total += c.total;
    complete += c.complete;
  }
  return { total, complete };
}

function renderBehaviour(b: OverviewBehaviour, indent: string): string[] {
  const lines: string[] = [];
  const actor = b.actor ? ` — Actor: ${b.actor}` : '';
  lines.push(`${indent}- **[${b.name}](${b.path})** \`[${b.state}]\`${actor}`);
  for (const impl of b.implementations) {
    const tests = impl.testCount > 0
      ? `, ${impl.testCount} test${impl.testCount !== 1 ? 's' : ''}`
      : ' ⚠ no tests';
    lines.push(`${indent}  - [${impl.name}](${impl.path}) \`[${impl.state}]\` (${impl.commitCount} commit${impl.commitCount !== 1 ? 's' : ''}${tests})`);
  }
  for (const sub of b.subBehaviours) {
    lines.push(...renderBehaviour(sub, indent + '  '));
  }
  return lines;
}

function formatOverview(intents: OverviewIntent[]): string {
  const now = new Date().toISOString().slice(0, 10);
  const lines: string[] = [];

  lines.push('# Project Overview');
  lines.push('');
  lines.push('<!-- Auto-generated by `taproot overview` — do not edit manually -->');
  lines.push(`<!-- Last updated: ${now} -->`);
  lines.push('');
  lines.push('Compact summary for AI agents. Read this before diving into individual taproot documents.');
  lines.push('');

  if (intents.length === 0) {
    lines.push('_No intents defined yet. Run `/tr-intent` to create one._');
    lines.push('');
    return lines.join('\n');
  }

  let totalBehaviours = 0;
  let totalImpls = 0;
  let totalComplete = 0;

  for (const intent of intents) {
    lines.push(`## [${intent.name}](${intent.path}) \`[${intent.state}]\``);
    lines.push('');
    if (intent.goal) {
      lines.push(`**Goal:** ${intent.goal}`);
      lines.push('');
    }
    if (intent.behaviours.length === 0) {
      lines.push('_No behaviours yet._');
      lines.push('');
    } else {
      for (const b of intent.behaviours) {
        lines.push(...renderBehaviour(b, ''));
        const c = implCounts(b);
        totalBehaviours++;
        totalImpls += c.total;
        totalComplete += c.complete;
        // count sub-behaviours toward totals
        const countSubs = (sub: OverviewBehaviour) => {
          totalBehaviours++;
          for (const s of sub.subBehaviours) countSubs(s);
        };
        for (const sub of b.subBehaviours) countSubs(sub);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(
    `${intents.length} intent${intents.length !== 1 ? 's' : ''} · ` +
    `${totalBehaviours} behaviour${totalBehaviours !== 1 ? 's' : ''} · ` +
    `${totalImpls} implementation${totalImpls !== 1 ? 's' : ''} · ` +
    `${totalComplete}/${totalImpls} complete`
  );
  lines.push('');

  return lines.join('\n');
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function runOverview(options: { taprootDir: string; cwd?: string }): Promise<string[]> {
  const { taprootDir } = options;
  if (!existsSync(taprootDir)) return [];

  const tree = walkHierarchy(taprootDir);
  const intents = tree.children
    .filter(c => c.marker === 'intent')
    .map(buildIntent);

  if (intents.length === 0) return [];

  const content = formatOverview(intents);
  const outputPath = join(taprootDir, 'OVERVIEW.md');
  writeFileSync(outputPath, content, 'utf-8');

  const rel = options.cwd
    ? outputPath.replace(options.cwd + '/', '').replace(options.cwd + '\\', '')
    : outputPath;
  return [`updated  ${rel}`];
}

export function registerOverview(program: Command): void {
  program
    .command('overview')
    .description('Generate OVERVIEW.md — compact project summary for AI context')
    .option('--path <path>', 'Taproot root directory (overrides config)')
    .action(async (options: { path?: string }) => {
      const { config } = loadConfig();
      const taprootDir = options.path ? resolve(options.path) : config.root;
      const msgs = await runOverview({ taprootDir });
      if (msgs.length === 0) {
        process.stdout.write('No intents found — nothing to summarize.\n');
      } else {
        for (const msg of msgs) process.stdout.write(msg + '\n');
      }
    });
}
