/**
 * CONFIGURATION.md generator.
 *
 * Produces the content installed at .taproot/CONFIGURATION.md — the primary
 * discoverability surface for agents completing configuration tasks.
 */

import { supportedLanguages } from './language.js';

export function buildConfigurationMd(): string {
  const langs = supportedLanguages().join(', ');

  return `# Taproot Configuration Reference

Edit \`.taproot/settings.yaml\` to configure taproot.

**After changing \`language\` or \`vocabulary\`:** run \`taproot update\` to regenerate skill files and adapters.
**After changing \`definitionOfDone\` or \`definitionOfReady\`:** no \`taproot update\` needed — these are read at runtime.

---

## language

Language pack for section headers, Gherkin keywords, and status values in skill files.

\`\`\`yaml
language: de
\`\`\`

**Supported values:** ${langs}

**Default:** English (omit the field)

**Requires \`taproot update\`:** yes — skill files and adapter descriptions are regenerated with translated terminology.

---

## vocabulary

Domain-specific term substitutions applied to all skill file output. Use this to replace taproot's default terminology with words native to your project's domain.

\`\`\`yaml
vocabulary:
  feature: story
  behaviour: acceptance criterion
  intent: epic
\`\`\`

**Format:** a YAML map of \`original: replacement\` string pairs. Keys are matched case-insensitively on whole words. Declaration order governs overlap — declare longer keys before their prefixes.

**Default:** no substitutions (omit the field)

**Requires \`taproot update\`:** yes — skill files are regenerated with the substituted terminology.

---

## definitionOfDone

Shell commands run as gates before implementation commits. Each command must exit 0 for the commit to proceed.

\`\`\`yaml
definitionOfDone:
  - condition: tests-passing
    run: npm test
  - condition: lint-clean
    run: npm run lint
\`\`\`

**Format:** a list of objects with \`condition\` (name shown in output) and \`run\` (shell command).

**Default:** baseline checks only (validate-format, validate-structure, tests-passing)

**Requires \`taproot update\`:** no — read at runtime by \`taproot dod\`.

---

## definitionOfReady

Shell commands run as gates before declaration commits (new impl.md). Each command must exit 0 for the commit to proceed.

\`\`\`yaml
definitionOfReady:
  - condition: spec-reviewed
    run: echo "Spec reviewed"
\`\`\`

**Format:** same as \`definitionOfDone\`.

**Default:** baseline checks only

**Requires \`taproot update\`:** no — read at runtime by the pre-commit hook.

---

## cli

CLI invocation prefix. Controls which command agents use when executing taproot CLI steps (e.g. in skill files that reference \`taproot dod\`, \`taproot link-commits\`, etc.).

\`\`\`yaml
cli: taproot
\`\`\`

**Default:** \`npx @imix-js/taproot\` (safe in any environment — works whether or not taproot is globally installed)

**Common overrides:**
- \`cli: taproot\` — use if taproot is globally installed (\`npm install -g @imix-js/taproot\`)
- \`cli: ./node_modules/.bin/taproot\` — use if taproot is a project \`devDependency\`

**Requires \`taproot update\`:** yes — the invocation block in agent adapter files is regenerated.

---

## Full example

\`\`\`yaml
version: 1
language: de
vocabulary:
  feature: story
  behaviour: acceptance criterion
definitionOfDone:
  - condition: tests-passing
    run: npm test
  - condition: lint-clean
    run: npm run lint
\`\`\`

---

*Generated by taproot. Run \`taproot update\` to refresh this file after upgrading.*
`;
}
